### ISSUE TITLE
images of structures not rendering in jupyter

### ISSUE THREAD

**Issue by lauradunphy** [KosinskiLab/AlphaPulldown#109]
Hello,

Thanks for creating this great tool! When I run output.ipynb, the figures from `parse_results_colour_chains` and `parse_results` do not render in either VSCode or Jupyter notebook. I do get text in the below format when I run the cells, however no images are displayed. `display_pae_plots` renders just fine. I tried just utilizing py3Dmol outside of your function and appear to have the same issue. Do you need to install any additional dependencies or extensions to visualize the results of py3Dmol?

```
 ==> Parsing a PDB/mmCIF file: $PATH/ranked_0.pdb
 ==> Parsing a PDB/mmCIF file: $PATH/ranked_1.pdb
 ==> Parsing a PDB/mmCIF file: $PATH/ranked_2.pdb
 ==> Parsing a PDB/mmCIF file: $PATH/ranked_3.pdb
 ==> Parsing a PDB/mmCIF file: $PATH/ranked_4.pdb
```

Many thanks,
Laura

**Comment by henrywotton** [comment]
Hi Laura,

Sorry it seems other users have also reported the same issue with displaying the 3D models recently and I'm looking into it right now and aim to get back to you later.

Cheers

**Comment by henrywotton** [comment]
Hi @lauradunphy 

It turned out that the issue came from the outdated py3Dmol package. Could you please, within the same conda env you created for AlphaPulldown, run ```pip install py3Dmol==2.0.1``` then ```jupyter-lab```. I have tried it myself and it works now with updated py3Dmol.

Please let me know if this solution also works for you and leave the issue open just in case other users may have the same problem. 

Yours
Dingquan

**Comment by lauradunphy** [comment]
Hi Dingquan,

Updating the pyD3mol package also worked for me! Thanks so much

Many thanks,
Laura
