### ISSUE TITLE
KeyError: 'template_confidence_scores'

### ISSUE THREAD

**Issue by Pooryamb** [KosinskiLab/AlphaPulldown#120]
Hi, 

I am trying to run AlphaPulldown in the pulldown mode. Even though it proceeds without any issue for some protein paits, it does not run successfully for some pairs. I have attached the error file. 
FYI: I have generated the MSAs using MMseqs2.

Could you please help me solve this issue?
[run_multimer_jobs_5254717_15_err.txt](https://github.com/KosinskiLab/AlphaPulldown/files/11179686/run_multimer_jobs_5254717_15_err.txt)

Best,

**Comment by henrywotton** [comment]
Hi @Pooryamb 

Sorry I haven't got this error before. You mentioned that some of the jobs are finished without this error. Could it be that you've calculated the feature pickles for some jobs using another version of AlphaPulldown or AlphaFold? The latest version of AlphaPulldown is 0.30.4 

It'll helpful if you could find out which protein gave this error and maybe send us the corresponding pickle file? 

Cheers

**Comment by henrywotton** [comment]
Hi @kashyapchhatbar ,

Many thanks for your advice and indeed the mk_mock_template caused the errors here. I'm now working to update this function instead of modifying the AlphaFold's codes. ```mk_mock_template``` was added in the latest version of AlphaPulldown as some of extra features we are currently developing would need mock empty template features. 

I will test my modifications and publish another release later. Thanks again for your effort.

Cheers

**Comment by henrywotton** [comment]
@Pooryamb 

Hi now you could try again after you upgrade to 0.30.5 version of AlphaPulldown. I've tested on my side and it worked. Hope it works for you, too.

Cheers
