### ISSUE TITLE
Error for specific proteins

### ISSUE THREAD

**Issue by roderickslieker** [KosinskiLab/AlphaPulldown#233]
I've set up a conda environment (Miniconda, python 3.10, latest alphafold (2.3.2) and alphapulldown (1.0.3) plus all dependencies according to the specifications). This seems to work well and it generates pkl files for multiple proteins, however I have noticed that for specific proteins I get the following error:

ValueError: min() arg is an empty sequence

which seems to originate from TemplateAtomMaskAllZerosError. The explanation is not entirely clear to me ("An error indicating that template mmCIF had all atom positions masked.") also because this protein is part of your example fasta file. 

Full error message attached and input fasta. The error arises for protein P22090, but also for, for example P42771 and Q8N726. In all cases the crash occurs for the mmcif file 6y32 (but runs fine across this file for others). I thought the file may be corrupt so I replaced it with a fresh download, but that did not solve the issue. 

[counts.txt](https://github.com/KosinskiLab/AlphaPulldown/files/13817975/counts.txt)
[Sequences.txt](https://github.com/KosinskiLab/AlphaPulldown/files/13817976/Sequences.txt)

**Comment by roderickslieker** [comment]
Follow up on this, it seems to require a default value in template.py:

 raise TemplateAtomMaskAllZerosError(
        'Template all atom mask was all zeros: %s_%s. Residue range: %d-%d' %
        (pdb_id, chain_id, min(mapping.values(), default=0) + mapping_offset,
         max(mapping.values(), default=0) + mapping_offset))

This is working (i.e. I am getting a pkl file), but I am not sure whether this is correct and what the default value should be?

**Comment by dingquanyu** [comment]
Hi @roderickslieker  
Thanks for the update! Indeed as you suggested, it needs something other than None here but somehow in the case of this protein, the mmseqs result led to a mapping.values() that is None. This fix you tried would get rid of this error but perhaps  we still have to fix the format problem coming from a3m file. Will work on that.

Cheers
Dingquan Yu

**Comment by gebauer** [comment]
Just stumbled here with the same problem, but a different protein... The "hack" works, but frankly I have no idea what the implications are for the downstream processes..?

**Comment by gebauer** [comment]
Hi @roderickslieker,

thanks for the warning. Did you manage to somehow get over this error? 
I have a different protein making error: 4jzl 

Best
Jan

**Comment by roderickslieker** [comment]
Ah I meant that I wouldn't use the -as you describe it - hack. The tool is really cool and I hope to get it to work.

**Comment by dingquanyu** [comment]
> Hi Jan, no I wouldn't use it. I ran into more problems downstream when doing the actual pulldown:ValueError: operands could not be broadcast together with shapes (4095,1276) (1,1314) (4095,1276). I am not sure whether this is the result of this modification. @dingquanyu the label is help wanted which suggests that this is user error. Can you clarify how to solve these errors (and whether subsequent errors are related)?

Hi @gebauer and @roderickslieker 

Sorry this error caused even more crashes downstream. My take on this is that something wrong with the formatting and reformatting inside the pipeline but haven't got through it so far. May I ask @gebauer if any other proteins other than 4jzp have given you the same error? 

Yours scinerely,
Dingquan

**Comment by gebauer** [comment]
Hi @dingquanyu ,

I am just starting with AlphaPulldown - so not so much additional errors yet.
I have a list of only 10 preys. From this P84090 gives me the error.
I  am currently running mmseq2, will try with the AF pipeline as well... 

For P84090 it failed for multiple PDBs (I entered the following in th obsolete.pdb, but stopped as it conitued to throw errors with further PDBs):
4JZP
4JPN
1R05
1AN2

What is obvious with this file, is its shortness 🤔

>sp|P84090|ERH_HUMAN Enhancer of rudimentary homolog OS=Homo sapiens OX=9606 GN=ERH PE=1 SV=1
MSHTILLVQPTKRPEGRTYADYESVNECMEGVCKMYEEHLKRMNPNSPSITYDISQLFDF
IDDLADLSCLVYRADTQTYQPYNKDWIKEKIYVLLRRQAQQAGK

Best
Jan

**Comment by gebauer** [comment]
> Hi Jan, no I wouldn't use it. I ran into more problems downstream when doing the actual pulldown:ValueError: operands could not be broadcast together with shapes (4095,1276) (1,1314) (4095,1276). I am not sure whether this is the result of this modification. @dingquanyu the label is help wanted which suggests that this is user error. Can you clarify how to solve these errors (and whether subsequent errors are related)?

I got the exact results even with the "vanilla" AlphaPulldown. So this is a general problem with mmseq. I wonder whether we are the only two using mmseq or if there is anything special... 🤔

**Comment by roderickslieker** [comment]
Hi Jan, yes I was aware that the issue was mmseq related. I am now running it without it. Hopefully with more luck..

**Comment by macwiatrak** [comment]
Hey, I am getting the same error running MMSeq2 for a bunch of proteins, including O14798, P01282, P32745 and Q9Y5U5. Did anybody try using native MMSeq2/ColabFold implementation? Wondering whether this relates to AlphaPulldown or directly to MMSeq2.

**Comment by Qrouger** [comment]
Hey, I have more information about this issue. In fact the pdb base is updated frequently. And by a mechanism I don't understand the mmseq want to align with new cif file present in the pdb database. But you don't get it in local because you download pdb database before the update.
https://files.rcsb.org/pub/pdb/data/assemblies/mmCIF/
![Screenshot from 2024-03-01 15-51-06](https://github.com/KosinskiLab/AlphaPulldown/assets/144003341/e80284f5-ddda-46cc-b303-a3825c2ed8f9)


So for fixe that you just have to download all database regularly or the file you are missing.

Quentin Rouger.

**Comment by gebauer** [comment]
> Hey, I have more information about this issue. In fact the pdb base is updated frequently. And by a mechanism I don't understand the mmseq want to align with new cif file present in the pdb database. But you don't get it in local because you download pdb database before the update. https://files.rcsb.org/pub/pdb/data/assemblies/mmCIF/ 
> So for fixe that you just have to download all database regularly or the file you are missing.
> 
> Quentin Rouger.

Sorry, I tried to understand what you are saying - but somehow I am missing some information (or insight😬)

I guess you are running mmseqs NOT locally (so option 1 in alphapulldown)? Even if you would run it locally I guess mmseqs does not need the PDB structures, because it normally only uses sequence information AFAIK.
The alignment to PDB structures is done by AlphaPulldown (I guess) and it normally uses the pdb_mmcif database from the AlphaFold installation. The database entries you are linking above are ASSEMBLIES so they obviously have different numbers, for different possible or speculated biological assemblies. Those, however, should not matter for an alignment nor for the structure prediction, as we are only using a single chain here any way...

Am I totally on the wrong path here? 

If you really got it to work with above assemblies database could you explain how? Or have you "only" update the PDB Database and that did the trick?

Best
Jan

**Comment by Qrouger** [comment]
Hi, Sorry for this misunderstanding.
I try to running mmseqs2 remotely (option1). 
And this command allow to do this :
create_individual_features.py \
  --fasta_paths=example_1_sequences.fasta \
  --data_dir=<path to alphafold databases> \
  --output_dir=<dir to save the output objects> \ 
  --skip_existing=False \
  --use_mmseqs2=True \
  --max_template_date=<any date you want, format like: 2050-01-01> \ 
  --seq_index=<any number you want or skip the flag to run all one after another>
So for create individual feature you need the alphafold database with PDB. 
That what I do.

Im not sure with the option 2 but obviously he also uses the AlphaFold database because it's a flag.
Yes your are right about the database it's not the good one. That was just to show the date which is recent.
https://files.rcsb.org/pub/pdb/data/structures/divided/mmCIF/y3/
![Screenshot from 2024-03-05 13-22-46](https://github.com/KosinskiLab/AlphaPulldown/assets/144003341/91f532c3-4109-4d51-8456-0d0e68de8575)

The hypothesis is AlphaPulldown mmseq method want to use alignement file who are not download locally in the pdb (because they are too recent and are not download). 

If this hypothesis is right you "just" have to update frequently the database. I haven't had time to try yet because the download takes a long time.

I hope that it's clearer.

Quentin Rouger.

**Comment by roderickslieker** [comment]
Hi Quentin, thanks for your replies. I am not sure I get it what you mean, but just to clarify, I ran these proteins more or less on the same day I downloaded the database.. Some proteins run with the mmseq method and some don't, and for those that don't the 'long' method without mmseq works somehow. So I have the pkl files now for a bunch of proteins. 

Unfortunately the next part of the code (pulldown mode) is still not working. 

From this script: run_multimer_jobs.py --mode=pulldown

ValueError: operands could not be broadcast together with shapes (4095,794) (1,1409) (4095,794) 

I hope that there will be a solution to this all at some point!

Roderick

**Comment by dingquanyu** [comment]
> Hi Quentin, thanks for your replies. I am not sure I get it what you mean, but just to clarify, I ran these proteins more or less on the same day I downloaded the database.. Some proteins run with the mmseq method and some don't, and for those that don't the 'long' method without mmseq works somehow. So I have the pkl files now for a bunch of proteins.
> 
> Unfortunately the next part of the code (pulldown mode) is still not working.
> 
> From this script: run_multimer_jobs.py --mode=pulldown
> 
> ValueError: operands could not be broadcast together with shapes (4095,794) (1,1409) (4095,794)
> 
> Edit: I wonder whether you can actually mix both methods and the answer is probably not.. I hope that there will be a solution to this all at some point!
> 
> Roderick

Hi Roderick,

Sorry that this error occurred. Could you attach the full error log? Thanks in advance.

Yours
Dingquan

**Comment by roderickslieker** [comment]
Hi Dingquan,

Yes attached!
[Pulldown.txt](https://github.com/KosinskiLab/AlphaPulldown/files/14497398/Pulldown.txt)

The result of the following code:
_run_multimer_jobs.py --mode=pulldown --num_cycle=3 --num_predictions_per_model=1 --output_path=/exports/archive/dermatlab-data/Roderick/PullDown_out --data_dir=/exports/archive/dermatlab-data/Roderick/Database --protein_lists=baits.txt,candidates.txt --monomer_objects_dir=/exports/archive/dermatlab-data/Roderick/Data_out --job_index=1 --compress_result_pickles=False -remove_result_pickles=False_

Where baits is a single bait list, candidates multiple proteins with pkl files in the folder. 

Roderick

**Comment by gebauer** [comment]
@Qrouger  I aprreciate every help and any attempt to bring us closer to this problem. However, for me updating the PDB database didn’t do the trick. 

I currently focus on this entry. It’s of no particular interest, but it’s small and thereby easy to test with:
>P84090
MSHTILLVQPTKRPEGRTYADYESVNECMEGVCKMYEEHLKRMNPNSPSITYDISQLFDFIDDLADLSCLVYRADTQTYQPYNKDWIKEKIYVLLRRQAQQAGK

This gives me always the error in AlphaPulldown with the mmseqs option. 
If I run all entries traditionally, everything works fine. However, as mmseqs is multiple times (at least 10x) faster, it would be very nice for bigger datasets.
In Colabfold_batch, I can predict this single protein with no problem. (@macwiatrak)

What is curious that there are quite a lot of very similar hits – the one which gives problems is 4jzl. And this is not similar at all. With only 5% I have no idea why it actually pops up. Also structurally, there is nothing… 
If I am not mistaken the function which gives us an error prunes bad amino acids and I can easily understand that this gives zero good amino acids. When I run colabfold_batch 4jzl is not used or suggested. So where does it come from?

Alignment of template structures...
<img width="964" alt="image" src="https://github.com/KosinskiLab/AlphaPulldown/assets/244549/64208e3e-1619-4754-b224-3606a2b51bb0">

Percent identity:
<img width="814" alt="image" src="https://github.com/KosinskiLab/AlphaPulldown/assets/244549/27befac7-9746-4ef7-bc24-ecc88e4f820e">


Best
Jan

**Comment by macwiatrak** [comment]
Thanks @gebauer! Did you try to run mmseqs2 with ColabFold and then running AlphaPulldown using the MSA from ColabFold? It seems like this would be the best way around now until we can run mmseqs2 with AlphaPulldown.

**Comment by gebauer** [comment]
@macwiatrak Yes I tried that and I get the same error as @roderickslieker 
`ValueError: operands could not be broadcast together with shapes (4095,1058) (1,1616) (4095,1058)`

I even cut down my inputs to be able to get all pkl files searched by mmseqs2 (was very difficult, because there are so many Uniprots which do not process, essentially the whole "short example" from your tutorial.), but even then - without mixed alignments - I get the above error. So somehow we have two problems
(1) The implementation of mmseqs in AF-Pulldown does notwork for every (or even most) Uniprot entries
(2) The produced alignment cannot be used in a prediction.

I was just wondering, did mmseqs worked for anyone before? Maybe we have strange configuration here, because it seems so broken 🤔

Best
Jan

**Comment by dingquanyu** [comment]
Hi all, @gebauer, @macwiatrak,  @Qrouger, @roderickslieker 

Thanks for your extra help and comments. I'm now modifying mmseqs2 mode in AlphaPulldown on a branch so that it uses the template alignments from mmseqs2. The current version will still query against local PDB70 database within your local AlphaFold DBs after running mmseqs2. I guess this way of getting template alignments cause the incompatibilities in the shapes of feature matrices. 

I'm really sorry for this error and I will let you know when the modification work is finished and we can test it together. 

Yours
Dingquan

**Comment by dingquanyu** [comment]
Hi all, @gebauer, @macwiatrak, @Qrouger, @roderickslieker,

I've finished modifying the mmseqs2 mode and now it will generate template features using results from remote mmseqs2 alignment instead of local AlphaFold DB alignments. I tested on P32745 and P01282 and it worked for me. Would you mind checking out this branch: https://github.com/KosinskiLab/AlphaPulldown/tree/update-unittest-objects and test in your cases after pulling the changes?  I hope this can solve the issues with these particular proteins.

Yours
Dingquan

**Comment by macwiatrak** [comment]
Hey @dingquanyu, thanks for looking into this! I checked out the `update-unittest-objects` branch it worked well for me for P32745 and P01282 as well as multiple other proteins 🎉 ! Bear in mind that I have not yet run structure prediction on the individual features.

For others, I installed `alphapulldown` from source https://github.com/KosinskiLab/AlphaPulldown/blob/main/manuals/Developing.md .

**Comment by gebauer** [comment]
Hey @dingquanyu I am currently running a long prediction on my workstation, which I don't want to interrupt. Afterwards, I will happily test your branch 👍 Thanks for the effort!

**Comment by dingquanyu** [comment]
> Hey @dingquanyu, thanks for looking into this! I checked out the `update-unittest-objects` branch it worked well for me for P32745 and P01282 as well as multiple other proteins 🎉 ! Bear in mind that I have not yet run structure prediction on the individual features.
> 
> For others, I installed `alphapulldown` from source https://github.com/KosinskiLab/AlphaPulldown/blob/main/manuals/Developing.md .

Thanks @macwiatrak for your update! I'll wait until your test on the structural prediction steps before merging in that branch. fingers crossed.

**Comment by roderickslieker** [comment]
@dingquanyu thanks Dingquan. I had to re-download the UniRef to a newer version, but after that it seems to work! At least our protein of interest worked using mmseq. Let's hope this solved the issue(s)!

**Comment by dingquanyu** [comment]
> Update2: I was able to run all proteins of interest in a couple of hours. Really nice, thanks @dingquanyu! The pulldown is also working on these files! 😎

Nice! Thanks for the update @roderickslieker and glad it finally worked. I will close this issue for now but feel free to reopen it if any of the cases failed despite of the updates.
