### ISSUE TITLE
IndexError when predicting monomers with more than 3 recycles

### ISSUE THREAD

**Issue by maurerv** [KosinskiLab/AlphaPulldown#272]
# Problem Description

When running monomer prediction with more than 3 recycles the inference pipeline fails at: https://github.com/KosinskiLab/AlphaPulldown/blob/f25cd086c3c2569c4391321c270c09de9051dc57/alphapulldown/predict_structure.py#L156 with a JAX index error (see attached log [slurm-49450816.txt](https://github.com/KosinskiLab/AlphaPulldown/files/14448256/slurm-49450816.txt)).

I have not tried this particular case using Alphafold directly.

# Reproducible Example

Input for run_multimer_jobs.py

_monomer_test.txt_
```
Q8I5K4,1
```

_monomer_test.sbatch_
```
#!/bin/bash
#SBATCH --time=2-00:00:00

#qos sets priority
#SBATCH --qos=high

#SBATCH -p gpu-el8
#SBATCH -C "gpu=A40|gpu=A100"
#SBATCH --gres=gpu:1
#SBATCH -N 1
#SBATCH --ntasks=8
#SBATCH --mem=128000

module load Anaconda3
module load CUDA/11.8.0
module load cuDNN/8.7.0.84-CUDA-11.8.0
source activate AlphaPulldown

BASE_PATH="/path/to/project/directory"
run_multimer_jobs.py  \
  --mode=homo-oligomer \
  --num_cycle=5 \
  --num_predictions_per_model=1 \
  --output_path=${BASE_PATH}/processing \
  --data_dir=/scratch/AlphaFold_DBs/2.3.0 \
  --oligomer_state_file=${BASE_PATH}/configuration/monomer_test.txt \
  --monomer_objects_dir=${BASE_PATH}/processing/monomers \
  --job_index=1
```

Monomeric features were created using:

```
#!/bin/bash

sbatch <<EOL
#!/bin/bash

#SBATCH --time=96:00:00
#SBATCH --qos=high
#SBATCH -N 1
#SBATCH --ntasks=8
#SBATCH --mem=64000

module load HMMER/3.3.2-gompi-2020b
module load HH-suite/3.3.0-gompi-2022a
module load Anaconda3
source activate AlphaPulldown

BASE_PATH="/path/to/project/directory"
create_individual_features.py \
  --fasta_paths=${BASE_PATH}/data/merged.fasta \
  --data_dir=/scratch/AlphaFold_DBs/2.3.0 \
  --save_msa_files=False \
  --output_dir=${BASE_PATH}/processing/monomers \
  --use_precomputed_msas=False \
  --max_template_date=2050-01-01 \
  --skip_existing=False \
  --seq_index=$SLURM_ARRAY_TASK_ID
EOL
```

_merged.fasta_
```
>Q8I5K4
MTGSDEEFEIGDILEIKKKKNGFIYLVKWKGYSDDENTWEPESNLIHLTTFKKKMESLKT
NFLSKANETNGDGKILKNHILAPTQEDDSIKSKGRSSLAPRRKMSRKSLTNKLENKKNLS
LSDNSLKKSDEEDNESVKHENHVNDGNLLNVEDVYSVRIKNKKLEFLASLKNESPQWVEE
TNIRRTGHLNIKVNDFKRYVRRKKSSRGNRIVIKNLHNVGDELYISVIHNINNKEIHSLY
PSKVIEYIYPQELLNFLLSRLRYRTA
```

# Environment

I ran alphapulldown 1.0.4 using the conda environment outlined in [ap_environment.txt](https://github.com/KosinskiLab/AlphaPulldown/files/14448250/ap_environment.txt)

**Comment by dingquanyu** [comment]
Unfortunately, this problem roots in AlphaFold's module.py, as shown here: https://github.com/google-deepmind/alphafold/blob/632ef575c64eff9eb5ed96c8c7b055bf675421ac/alphafold/model/modules.py#L331

In the case of monomer modelling, Deepmind never exposed num_recycles to the users thus num_recycles is always hard-coded as 3 in the configuration. The batch size is 4 in the above snipped, hard-coded as well by Deepmind. Thus, when num_recycles is smaller or equals to 3, this line of ```num_ensemble = batch_size // (self.config.num_recycle + 1)``` assigns num_ensemble to 1. However, if num_recyle is greater than 3, then ```num_ensemble = batch_size // (self.config.num_recycle + 1)``` will make num_ensemble to 0. ```num_ensemble=0``` will mess up the downstream data processing like here: 
https://github.com/google-deepmind/alphafold/blob/632ef575c64eff9eb5ed96c8c7b055bf675421ac/alphafold/model/modules.py#L336
and here https://github.com/google-deepmind/alphafold/blob/632ef575c64eff9eb5ed96c8c7b055bf675421ac/alphafold/model/modules.py#L166

Multimer modelling works for whichever number of recyles cuz in multimer_module.py, this step is completely got rid off. 
I think the solution now is that we should add an extra check in AlphaPulldown so that if it models a monomer structure, we set the upper limit of num_recyles.

**Comment by jkosinski** [comment]
Crazy!  I think ColabFold might have fixed that by editing this line:
https://github.com/sokrypton/alphafold/blob/7c09316f71893e532bc15528cce4c1d3cb705f8f/alphafold/model/modules.py#L421
Do I understand that correct? Maybe we could do the same? Allowing for more recycles for monomers is a useful feature, esp. if they are big.

**Comment by dingquanyu** [comment]
> Crazy! I think ColabFold might have fixed that by editing this line: https://github.com/sokrypton/alphafold/blob/7c09316f71893e532bc15528cce4c1d3cb705f8f/alphafold/model/modules.py#L421 Do I understand that correct? Maybe we could do the same? Allowing for more recycles for monomers is a useful feature, esp. if they are big.

Thanks Jan you're right ColabFold guys got rid of this limit in these lines. We can do the same but it has to be done on our AlphaFold"s fork instead of AlphaPulldown.
