### ISSUE TITLE
num_predictions_per_model

### ISSUE THREAD

**Issue by hqdream** [KosinskiLab/AlphaPulldown#294]
--num_predictions_per_model=1 was used. However, this still generates 5 predictions per model, which is very time-consuming when trying to do a large number of predictions.

**Comment by hqdream** [comment]
Thank you very much for your kind reply.

Below is the command line I used to predict interactions:

run_multimer_jobs.py --mode pulldown --num_cycle 3 --num_predictions_per_model 1 --output_path ./pulldown --data_dir /mnt/Ddisk/alphafold-2.3.1/database_2.3/ --protein_lists baits.txt,candidates.txt --monomer_objects_dir . --compress_result_pickles True

This is a screenshot of the output result folder. It seems to have generated 5 predicitons per model if I understand the parameter correctly.
![results](https://github.com/KosinskiLab/AlphaPulldown/assets/53590024/3bd1a7a9-d36f-4dbf-9801-26929446d60d)

By the way, what dose the parameter " --num_cycle 3 " mean. Thank you.

 Qi

**Comment by dingquanyu** [comment]
Thanks for the update and the screenshot you attached showed you got exactly one prediction per model. Since there are 5 model setting in total, if you set num_prediction_per_model to be 5, then you will end up with 25 ranked_xx.pdb. The fact that you only got 5 ranked_xx.pdb means num_prediction_per_model=1 worked as instructed.

num_cycle mean the number of cycling described in AlphaFold's paper. Please refer to their publication on Nature for the detailed explanation.
