### ISSUE TITLE
File name too long owing to folder nomenclature

### ISSUE THREAD

**Issue by ordavies** [KosinskiLab/AlphaPulldown#431]
This is an excellent package for running AlphaFold that allows an impressive level of control over msa and template use. However, it is very easy for runs to fail owing to file names being too long as the folder names are formatted as 'protein_A_and_protein_A_and_protein_B_and' etc. This is a particular problem when using regions of a protein and templates as each chain is formatted as 'protein_A.pdbid.cif.A_xx-xxx'. I haven't been able to run some computationally small models owing to the resultant file names being too long, which is a great shame as it limits this otherwise excellent package.

Is it possible to forcibly rename the output file directory (the one below that specified by --output_directory)?

Alternatively, could the folder nomenclature be made more succinct by using 'protein_A_2' rather than 'protein_A_and_protein_A' etc?

As a secondary issue, note that version 2.0.0b6 crashes with current biopython (1.84), as it relies on importing SCOPData from Bio.Data, which has been deprecated from SCOPData to PDBData . This can be solved by installing biopython 1.81.

**Comment by DimaMolod** [comment]
Hi @ordavies and thanks for your comments and for using our software.
I think the both your issues can be solved quite easily. The naming of the output directories like `protein_and_protein...` follow the old AP convention and can be turned off if you use `run_structure_prediction.py` script instead of `run_multimer_jobs.py`. In this script there is a flag called `use_ap_style` that names the output dirs the old way. If you want to name the output dir directly, you can use this script with a flag `--output_directory` directly. You can also use our [new snakemake pipeline](https://github.com/KosinskiLab/AlphaPulldown?tab=readme-ov-file#snakemake-alphapulldown) that uses shorter output folder nomenclatures.
Regarding your second question, it shouldn't be the problem if you use alphafold from our fork because of [this commit](https://github.com/KosinskiLab/alphafold/commit/0ad48dd8d55f4f13df577fc24002a9ad1f9fec39). This also removes biopython warning messages about deprecation of SCOPData, so maybe you could just update your alphafold submodule?

**Comment by ordavies** [comment]
Many thanks for your reply. Yes, the run_structure_prediction.py script nicely solves this problem. I have observed a couple of issues using this:

The input flag --input=ProteinA:2:1-100,ProteinB:2:1-100 leads to it firstly generating models of only ProteinA dimers, and then trying to generate ProteinB dimers (but stopping as there are already output files). This can be overcome by changing the flag to --input=ProteinA:2:1-100+ProteinB:2:1-100, which leads to the generation of 2:2 complexes.

PAE plots are not generated as it tried to use the old naming system for these files despite using the folders having the designated names, which generates names that are too long to be written. The error prevents downstream actions such as ranking from being performed. I can't see a way of overcoming this.

Also, the following two issues apply both to structure_prediction.py and run_multimer_jobs.py:

When using a specified amino-acid sequence, the feature metadata are not found as it expects the json file to be in the format proteinA_xx-xxx_feature_metadata_*.json, whereas it is saved as proteinA_feature_metadata_*.json. It works if the json file is renamed. This issue does not affect the pkl file.

Using Truemultimer mode, the description.csv is read ok by create_individual_features.py step and the pdb_hits.sto file indicates that this has been applied correctly. However, it generates an error at the structure prediction stage. E.g. the csv file
>ProteinA,pdb.cif,A
gives the error
KeyError: '>ProteinA'
Is it necessary to include the description file at this point or is this just intended to adjust the name of the protein to match the features file? I can run it without this flag as long as the name of the target protein is changed to e.g. proteinA.pdb.cif.A.

Thanks again for your help!

**Comment by DimaMolod** [comment]
Many thanks for all your testing and reports! Much appreciated.
I will start with the last question about TrueMultimer mode: no, you don't need to provide description file again, since the features were already calculated at the previous step. The only additional flag you need to provide for modeling is the boolean `--multimeric_template` as this effectively disables multimeric masking in AF. 
Now moving on to your first question:
>The input flag --input=ProteinA:2:1-100,ProteinB:2:1-100 ...

yes, this leads to modeling a dimer of protein A and a dimer of protein B in the same output_directory. This happens because `run_strucutre_prediction.py` uses '+' as the default separator, whereas `run_multimer_jobs.py` keeps the old syntax for back-compatibility reasons. [This is](https://github.com/KosinskiLab/AlphaPulldown/blob/main/alphapulldown/scripts/run_multimer_jobs.py#L64-L65) how the transition between syntaxes is done internally. I know its confusing, but that's the way it is, sorry for that :-)
I will also fix the hardcoded PAE naming part, thanks again for reporting this!
