### ISSUE TITLE
How to speed up the first step for model prediction?

### ISSUE THREAD

**Issue by nduan1** [KosinskiLab/AlphaPulldown#49]
Hi,

Can I allocate more CPUs to the first step of prediction? I can't find the argument to assign more CPUs. I have over 30,000 proteins that need to be predicted, it still needs to take days even though I have split it up into 200 sub-jobs. Can I have some suggestions?

Thanks,

Ning

**Comment by henrywotton** [comment]
Hi,

Sorry we built our package based on AlphaFold's pipeline and the MSA subprocess was inherited from AlphaFold, which runs on 1 CPU. Besides, running those 200 jobs on multiple CPUs may not necessarily speed up the process because when the CPUs all reading from the same file, they could slow down each other's I/O. 

We will closely monitor updates on AlphaFold and evaluate whether we'll add this feature to AlphaPulldown in the future.

Yours,
Dingquan

**Comment by th-of** [comment]
> Hi,
> 
> Sorry we built our package based on AlphaFold's pipeline and the MSA subprocess was inherited from AlphaFold, which hard-coded the number of CPUs. Besides, running those 200 jobs on more CPUs may not necessarily speed up the process because when the CPUs all reading from the same file, they could slow down each other's I/O.
> 
> We will closely monitor updates on AlphaFold and evaluate whether we'll add this feature to AlphaPulldown in the future.
> 
> Yours, Dingquan

This is extremely unfortunate, 8 and 4 CPU threads is nothing. I have modified AlphaFold to run these subprocesses with more CPUs, which works fine. Unfortunately this does not work with AlphaPulldown.
