### ISSUE TITLE
why python==3.7.* ?

### ISSUE THREAD

**Issue by schluenz** [KosinskiLab/AlphaPulldown#75]
what is the reason for the Python==3.7.* requirement?  Code seems to run fine with e.g. python 3.9.13

**Comment by henrywotton** [comment]
Hi,

That's because we'd like to stay as close as possible to AlphaFold. Please check their Dockerfile here:
https://github.com/deepmind/alphafold/blob/5cb2f8c480aa8314c02a93c6fbfc3f48f0ce8af0/docker/Dockerfile#L62
in which they specified python 3.7 but feel free to test it on different versions of python. 

Cheers
Dingquan

**Comment by schluenz** [comment]
Hi Dingquan, 

yeah I know, but alphafold works nicely with python 3.9, and the alphafold requirements actually do not include python==3.7 (https://github.com/deepmind/alphafold/blob/main/requirements.txt). But I frankly just like the convenience of pip install alphapulldown (without --ignore-requires-python which can be cumbersome). It's not really an issue, so I'll simply close it. 

Cheers, Frank.
