### ISSUE TITLE
Interpretation of mpDockQ/pDockQ 

### ISSUE THREAD

**Issue by CelineGrech** [KosinskiLab/AlphaPulldown#96]
Hi, regarding the mpDockQ/pDockQ score reported in the predictions_with_good_interpae.csv, does it mean that either mpDockQ or pDockQ is reported? Also, does mpDockQ has the same threshold as the pDockQ where if the model with pDockQ>0.5 is likely to be correct (Elofsson et al., 2021). Thank you

**Comment by dennissv** [comment]
Hi, thanks for a cool tool! It seems like if there's two chains the pDockQ is reported and if there's more than that the mpDockQ is returned instead, is this right?

I also wonder if these values might be incorrect since they seem to consistently be much higher than if I run them with the original scoring script from https://gitlab.com/ElofssonLab/FoldDock. Or does this scoring model differ from the original by design? Even predictions that doesn't seem to interact at all can have a reported pDockQ score of 0.6 or over and predictions with any interacting residues mainly have ~0.74. This can also be seen in the supplied examples.

**Comment by henrywotton** [comment]
Hi,

Sorry this seems to be an error and many thanks for your reports and comments. I will look into the scripts and get back to you later. 

Cheers

**Comment by henrywotton** [comment]
Hi @dennissv ,

It's me again and now the error in the pDockQ calculation is fixed. Could you re-download the singularity image again and try it on your models? I have tested a couple of mine and it gave me the same values as FoldDock's script but please let me know if there are disagreements in your cases.

Cheers

**Comment by dennissv** [comment]
Hi @henrywotton , Thank you for your reply and looking into this so swiftly! I have updated my environment to v0.30 but where can I find the new singularity image? The only one I can see at https://www.embl-hamburg.de/AlphaPulldown/downloads/ is the older one.

**Comment by henrywotton** [comment]
Hi @dennissv , I'm really sorry that the file on our server hasn't been updated on time. Could you try the same link now? It should give you the newer version of the singularity image

**Comment by dennissv** [comment]
@henrywotton No worries, I'm happy to report that the given mpDockQ/pDockQ score from the new image is identical to the score I get from the original FoldDock scoring script. Thanks again!
